/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallDeAgendamentoRouteImport } from './routes/call-de-agendamento'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PermissoesRouteImport } from './routes/permissoes'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as ClientesClienteIdRouteImport } from './routes/clientes.$clienteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallDeAgendamentoRoute = CallDeAgendamentoRouteImport.update({
  id: '/call-de-agendamento',
  path: '/call-de-agendamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissoesRoute = PermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesClienteIdRoute = ClientesClienteIdRouteImport.update({
  id: '/$clienteId',
  path: '/$clienteId',
  getParentRoute: () => ClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/call-de-agendamento': typeof CallDeAgendamentoRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/financeiro': typeof FinanceiroRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/permissoes': typeof PermissoesRoute
  '/produtos': typeof ProdutosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/solucoes': typeof SolucoesRoute
  '/suporte': typeof SuporteRoute
  '/usuarios': typeof UsuariosRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/call-de-agendamento': typeof CallDeAgendamentoRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/financeiro': typeof FinanceiroRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/permissoes': typeof PermissoesRoute
  '/produtos': typeof ProdutosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/solucoes': typeof SolucoesRoute
  '/suporte': typeof SuporteRoute
  '/usuarios': typeof UsuariosRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/call-de-agendamento': typeof CallDeAgendamentoRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/financeiro': typeof FinanceiroRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/permissoes': typeof PermissoesRoute
  '/produtos': typeof ProdutosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/solucoes': typeof SolucoesRoute
  '/suporte': typeof SuporteRoute
  '/usuarios': typeof UsuariosRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/call-de-agendamento'
    | '/clientes'
    | '/configuracoes'
    | '/contratos'
    | '/financeiro'
    | '/leads'
    | '/login'
    | '/permissoes'
    | '/produtos'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/relatorios'
    | '/solucoes'
    | '/suporte'
    | '/usuarios'
    | '/clientes/$clienteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/call-de-agendamento'
    | '/clientes'
    | '/configuracoes'
    | '/contratos'
    | '/financeiro'
    | '/leads'
    | '/login'
    | '/permissoes'
    | '/produtos'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/relatorios'
    | '/solucoes'
    | '/suporte'
    | '/usuarios'
    | '/clientes/$clienteId'
  id:
    | '__root__'
    | '/'
    | '/call-de-agendamento'
    | '/clientes'
    | '/configuracoes'
    | '/contratos'
    | '/financeiro'
    | '/leads'
    | '/login'
    | '/permissoes'
    | '/produtos'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/relatorios'
    | '/solucoes'
    | '/suporte'
    | '/usuarios'
    | '/clientes/$clienteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallDeAgendamentoRoute: typeof CallDeAgendamentoRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContratosRoute: typeof ContratosRoute
  FinanceiroRoute: typeof FinanceiroRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  PermissoesRoute: typeof PermissoesRoute
  ProdutosRoute: typeof ProdutosRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SolucoesRoute: typeof SolucoesRoute
  SuporteRoute: typeof SuporteRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-de-agendamento': {
      id: '/call-de-agendamento'
      path: '/call-de-agendamento'
      fullPath: '/call-de-agendamento'
      preLoaderRoute: typeof CallDeAgendamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissoes': {
      id: '/permissoes'
      path: '/permissoes'
      fullPath: '/permissoes'
      preLoaderRoute: typeof PermissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$clienteId': {
      id: '/clientes/$clienteId'
      path: '/$clienteId'
      fullPath: '/clientes/$clienteId'
      preLoaderRoute: typeof ClientesClienteIdRouteImport
      parentRoute: typeof ClientesRoute
    }
  }
}

interface ClientesRouteChildren {
  ClientesClienteIdRoute: typeof ClientesClienteIdRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesClienteIdRoute: ClientesClienteIdRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallDeAgendamentoRoute: CallDeAgendamentoRoute,
  ClientesRoute: ClientesRouteWithChildren,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContratosRoute: ContratosRoute,
  FinanceiroRoute: FinanceiroRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  PermissoesRoute: PermissoesRoute,
  ProdutosRoute: ProdutosRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  RelatoriosRoute: RelatoriosRoute,
  SolucoesRoute: SolucoesRoute,
  SuporteRoute: SuporteRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
